// Enriched mock dataset — demonstrates the metadata-first card model.
// New fields beyond the current manifest.json: tags, status, source_type, checksum,
// retention, owner, last_run (who/when/duration/result), size_bytes, change_count.
// The UI is bound generically so adding fields later only requires a facet/column config.

window.ARCHIVE_DATA = {
  pages: [
    {
      slug: "ipv4",
      title: "IPv4",
      oldid: "1348847330",
      collection: "Networking",
      tags: ["protocol", "layer-3", "foundational"],
      status: "fresh",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/w/index.php?title=IPv4&oldid=1348847330",
      host: "en.wikipedia.org",
      archived_at_utc: "2026-04-24T09:43:39Z",
      size_bytes: 842100,
      checksum: "sha256:b41c…9e2a",
      retention: "indefinite",
      owner: "j.rivera",
      change_count: 7,
      last_run: { by: "j.rivera", at: "2026-04-24T09:43:39Z", duration_ms: 4820, result: "ok" },
    },
    {
      slug: "bgp",
      title: "Border Gateway Protocol",
      oldid: "1350273192",
      collection: "Networking",
      tags: ["protocol", "routing", "internet-core"],
      status: "fresh",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/w/index.php?title=Border_Gateway_Protocol&oldid=1350273192",
      host: "en.wikipedia.org",
      archived_at_utc: "2026-04-24T09:42:53Z",
      size_bytes: 1210400,
      checksum: "sha256:7f02…c1d4",
      retention: "indefinite",
      owner: "j.rivera",
      change_count: 3,
      last_run: { by: "j.rivera", at: "2026-04-24T09:42:53Z", duration_ms: 6120, result: "ok" },
    },
    {
      slug: "dns",
      title: "Domain Name System",
      oldid: "1347240445",
      collection: "Networking",
      tags: ["protocol", "naming", "foundational"],
      status: "fresh",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/w/index.php?title=Domain_Name_System&oldid=1347240445",
      host: "en.wikipedia.org",
      archived_at_utc: "2026-04-24T09:42:53Z",
      size_bytes: 968300,
      checksum: "sha256:2ae1…8801",
      retention: "indefinite",
      owner: "j.rivera",
      change_count: 2,
      last_run: { by: "j.rivera", at: "2026-04-24T09:42:53Z", duration_ms: 5210, result: "ok" },
    },
    {
      slug: "tcp",
      title: "Transmission Control Protocol",
      oldid: "1349110024",
      collection: "Networking",
      tags: ["protocol", "layer-4", "foundational"],
      status: "stale",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/wiki/Transmission_Control_Protocol",
      host: "en.wikipedia.org",
      archived_at_utc: "2026-02-11T14:02:10Z",
      size_bytes: 1044000,
      checksum: "sha256:91cb…4f12",
      retention: "indefinite",
      owner: "k.okafor",
      change_count: 1,
      last_run: { by: "k.okafor", at: "2026-02-11T14:02:10Z", duration_ms: 4990, result: "ok" },
    },
    {
      slug: "tls",
      title: "Transport Layer Security",
      oldid: "1351007711",
      collection: "Security",
      tags: ["crypto", "protocol", "web"],
      status: "fresh",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/wiki/Transport_Layer_Security",
      host: "en.wikipedia.org",
      archived_at_utc: "2026-04-19T17:28:00Z",
      size_bytes: 1488900,
      checksum: "sha256:d0aa…7b19",
      retention: "indefinite",
      owner: "k.okafor",
      change_count: 4,
      last_run: { by: "k.okafor", at: "2026-04-19T17:28:00Z", duration_ms: 7140, result: "ok" },
    },
    {
      slug: "rfc-9293",
      title: "RFC 9293 — Transmission Control Protocol",
      oldid: null,
      collection: "RFCs",
      tags: ["rfc", "ietf", "layer-4"],
      status: "fresh",
      source_type: "rfc",
      source_url: "https://www.rfc-editor.org/rfc/rfc9293.html",
      host: "rfc-editor.org",
      archived_at_utc: "2026-04-22T11:10:00Z",
      size_bytes: 612500,
      checksum: "sha256:11fe…aa02",
      retention: "indefinite",
      owner: "m.sato",
      change_count: 1,
      last_run: { by: "m.sato", at: "2026-04-22T11:10:00Z", duration_ms: 2300, result: "ok" },
    },
    {
      slug: "rfc-8446",
      title: "RFC 8446 — TLS 1.3",
      oldid: null,
      collection: "RFCs",
      tags: ["rfc", "ietf", "crypto"],
      status: "fresh",
      source_type: "rfc",
      source_url: "https://www.rfc-editor.org/rfc/rfc8446.html",
      host: "rfc-editor.org",
      archived_at_utc: "2026-04-22T11:10:45Z",
      size_bytes: 508200,
      checksum: "sha256:3b77…19ce",
      retention: "indefinite",
      owner: "m.sato",
      change_count: 0,
      last_run: { by: "m.sato", at: "2026-04-22T11:10:45Z", duration_ms: 1890, result: "ok" },
    },
    {
      slug: "cidr",
      title: "Classless Inter-Domain Routing",
      oldid: "1340022918",
      collection: "Networking",
      tags: ["addressing", "routing"],
      status: "stale",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing",
      host: "en.wikipedia.org",
      archived_at_utc: "2025-12-02T08:00:00Z",
      size_bytes: 520000,
      checksum: "sha256:55ac…ee34",
      retention: "1 year",
      owner: "j.rivera",
      change_count: 0,
      last_run: { by: "j.rivera", at: "2025-12-02T08:00:00Z", duration_ms: 3410, result: "ok" },
    },
    {
      slug: "http-3",
      title: "HTTP/3",
      oldid: "1349900128",
      collection: "Web",
      tags: ["protocol", "http", "quic"],
      status: "fresh",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/wiki/HTTP/3",
      host: "en.wikipedia.org",
      archived_at_utc: "2026-04-20T22:14:07Z",
      size_bytes: 488700,
      checksum: "sha256:82bd…c901",
      retention: "indefinite",
      owner: "k.okafor",
      change_count: 2,
      last_run: { by: "k.okafor", at: "2026-04-20T22:14:07Z", duration_ms: 3020, result: "ok" },
    },
    {
      slug: "quic",
      title: "QUIC",
      oldid: "1348220011",
      collection: "Web",
      tags: ["protocol", "transport", "quic"],
      status: "fresh",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/wiki/QUIC",
      host: "en.wikipedia.org",
      archived_at_utc: "2026-04-18T10:02:44Z",
      size_bytes: 734200,
      checksum: "sha256:9abe…0d77",
      retention: "indefinite",
      owner: "k.okafor",
      change_count: 5,
      last_run: { by: "k.okafor", at: "2026-04-18T10:02:44Z", duration_ms: 4880, result: "ok" },
    },
    {
      slug: "ospf",
      title: "Open Shortest Path First",
      oldid: "1339882221",
      collection: "Networking",
      tags: ["protocol", "routing", "igp"],
      status: "stale",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/wiki/Open_Shortest_Path_First",
      host: "en.wikipedia.org",
      archived_at_utc: "2025-11-14T06:51:00Z",
      size_bytes: 602000,
      checksum: "sha256:4411…77aa",
      retention: "1 year",
      owner: "j.rivera",
      change_count: 1,
      last_run: { by: "j.rivera", at: "2025-11-14T06:51:00Z", duration_ms: 4010, result: "ok" },
    },
    {
      slug: "subnet",
      title: "Subnetwork",
      oldid: null,
      collection: "Networking",
      tags: ["addressing", "foundational"],
      status: "queued",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/wiki/Subnetwork",
      host: "en.wikipedia.org",
      archived_at_utc: null,
      size_bytes: 0,
      checksum: null,
      retention: "indefinite",
      owner: "j.rivera",
      change_count: 0,
      last_run: null,
    },
    {
      slug: "ipv6",
      title: "IPv6",
      oldid: null,
      collection: "Networking",
      tags: ["protocol", "layer-3", "addressing"],
      status: "failed",
      source_type: "wikipedia",
      source_url: "https://en.wikipedia.org/wiki/IPv6",
      host: "en.wikipedia.org",
      archived_at_utc: null,
      size_bytes: 0,
      checksum: null,
      retention: "indefinite",
      owner: "j.rivera",
      change_count: 0,
      last_run: { by: "j.rivera", at: "2026-04-24T09:50:00Z", duration_ms: 1200, result: "error: upstream 503" },
    },
    {
      slug: "mitm-paper",
      title: "A Taxonomy of MITM Attacks (paper)",
      oldid: null,
      collection: "Papers",
      tags: ["security", "research"],
      status: "fresh",
      source_type: "pdf",
      source_url: "https://example.org/papers/mitm-taxonomy.pdf",
      host: "example.org",
      archived_at_utc: "2026-03-30T15:00:00Z",
      size_bytes: 2140000,
      checksum: "sha256:ab12…90fe",
      retention: "5 years",
      owner: "m.sato",
      change_count: 0,
      last_run: { by: "m.sato", at: "2026-03-30T15:00:00Z", duration_ms: 8800, result: "ok" },
    },
  ],
};

// Initial job feed — the UI also appends new entries when operations run.
window.ARCHIVE_JOBS = [
  { id: "j-1042", action: "refresh_one", target: "IPv4", state: "complete", started: "2026-04-24T09:43:35Z", duration_ms: 4820, by: "j.rivera" },
  { id: "j-1041", action: "only_title", target: "RFC 8446 — TLS 1.3", state: "complete", started: "2026-04-22T11:10:40Z", duration_ms: 1890, by: "m.sato" },
  { id: "j-1040", action: "refresh_all", target: "14 pages", state: "complete", started: "2026-04-22T10:02:00Z", duration_ms: 62400, by: "k.okafor" },
];

// Optional override for backend API base URL.
// Default to same host so remote clients don't call their own localhost.
(() => {
  if (window.ARCHIVE_API_BASE) return;
  const host = (window.location && window.location.hostname) || "";
  const proto = window.location && window.location.protocol === "https:" ? "https:" : "http:";
  const inferred = host ? `${proto}//${host}:8010/api/v1` : "http://127.0.0.1:8010/api/v1";
  window.ARCHIVE_API_BASE = inferred;
})();
